version: '3'

services:
  dbupgrade:
    image: docker.whatsapp.biz/coreapp:v${WA_API_VERSION:?Run docker-compose with env var WA_API_VERSION (ex. WA_API_VERSION=2.21.4 docker-compose <command> <options>)}
    restart: on-failure
    command: ["/opt/whatsapp/bin/wait_on_mysql.sh", "/opt/whatsapp/bin/launch_within_docker.sh"]
    env_file:
      - db.env
    environment:
      WA_DB_UPGRADE: 1
    network_mode: bridge
